name: Construction d'un projet

on: # evenement
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest   # github met à dispo un container unbutu pour executer mes containers

    steps:
    - name: Téléchargement de la source
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    # cette partie consiste à generer le livrable
    - name: Build with Maven
      run: mvn -B package --file pom.xml


